### ISSUE TITLE
Cannot Run the Progam

### ISSUE THREAD

**Issue by SSDharmawansa** [Siceth/flp-genetic#1]
Can you help me to run this code in my VS code?

**Comment by Siceth** [comment]
Hello @SSDharmawansa. Please elaborate on your issue and explain what you've tried to do in running the program.

The main executable is [FLP_GA_WotC.py](https://github.com/Siceth/flp-genetic/blob/main/FLP_GA_WotC.py), which requires Python 3.6 or higher and the following dependencies to be installed:
- argparse
- packaging
- matplotlib
- pandas
- numpy
- progressbar

Any kind of stack trace will help me help you.

**Comment by SSDharmawansa** [comment]
Thank You for your response,

usage: FLP_GA_WotC.py [-h] -n FACILITIES -p POPULATION_SIZE -e ELITES -m
MUTATION_RATE -g GENERATIONS [-w] [-s] [-v] file
FLP_GA_WotC.py: error: the following arguments are required: file,
-n/--facilities, -p/--population-size, -e/--elites, -m/--mutation-rate,
-g/--generations
when I'm running FLP_GA_WotC.py file it shows this kind of error can you
help me to fix it?



Wish You,
Best Regards,
Sahan S Dharmawansa.

**Comment by SSDharmawansa** [comment]
If you have time I'll share my screen can you help me to fix it?
Thank You!

Wish You,
Best Regards,
Sahan S Dharmawansa.

**Comment by Siceth** [comment]
> usage: FLP_GA_WotC.py [-h] -n FACILITIES -p POPULATION_SIZE -e ELITES -m MUTATION_RATE -g GENERATIONS [-w] [-s] [-v] file FLP_GA_WotC.py: error: the following arguments are required: file, -n/--facilities, -p/--population-size, -e/--elites, -m/--mutation-rate, -g/--generations when I'm running FLP_GA_WotC.py file it shows this kind of error can you help me to fix it?

This is expected behavior, not an error. Per the usage line, the program requires you to pass in arguments, _for example_:
`python3 FLP_GA_WotC.py -n 100 -p 50 -e 5 -m 10 -g 120 Random100`

I don't have deep documentation for what each variable does, but the YouTube video covers the parameters and you can dig into the code to see where it's used. You can also see what other parameters are available with:

`python3 FLP_GA_WotC.py --help`
